## Aula 3 Video 1 - Entendendo os dados e o problema

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter

Download Dataset: [avaliacoes_usuario.csv](https://s3.amazonaws.com/caelum-online-public/machine-learning-aprendizado-supervisionado/avaliacoes_usuario.csv)

In [2]:
movies = pd.read_csv('datasets/avaliacoes_usuario.csv')

In [3]:
movies.head(5)

Titulo  Documentary  Sci-Fi  Mystery  Horror  Romance  \
0              Nixon (1995)            0       0        0       0        0   
1  Leaving Las Vegas (1995)            0       0        0       0        1   
2         Persuasion (1995)            0       0        0       0        1   
3               Babe (1995)            0       0        0       0        0   
4         Carrington (1995)            0       0        0       0        1   

   Thriller  Crime  Fantasy  Comedy  Animation  Children  Drama  Adventure  \
0         0      0        0       0          0         0      1          0   
1         0      0        0       0          0         0      1          0   
2         0      0        0       0          0         0      1          0   
3         0      0        0       0          0         1      1          0   
4         0      0        0       0          0         0      1          0   

      Duracao  Investimento  Gostou  
0  114.496547      7.930748       1  
1  110.140191     18.276555       1  
2  105.747597     16.582232       1  
3  126.131978     13.004553       1  
4   85.025469     14.418120       1

In [52]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 17 columns):
Titulo          678 non-null object
Documentary     678 non-null int64
Sci-Fi          678 non-null int64
Mystery         678 non-null int64
Horror          678 non-null int64
Romance         678 non-null int64
Thriller        678 non-null int64
Crime           678 non-null int64
Fantasy         678 non-null int64
Comedy          678 non-null int64
Animation       678 non-null int64
Children        678 non-null int64
Drama           678 non-null int64
Adventure       678 non-null int64
Duracao         678 non-null float64
Investimento    678 non-null float64
Gostou          678 non-null int64
dtypes: float64(2), int64(14), object(1)
memory usage: 90.1+ KB


In [4]:
Counter(movies['Gostou'])

Counter({1: 543, 0: 135})

In [48]:
print('Gostou {} %'.format((543/(135+543))*100))

Gostou 80.08849557522124 %


In [49]:
print('Não gostou {} %'.format((135/(135+543))*100))

Não gostou 19.911504424778762 %


In [7]:
caract = movies[movies.columns[1:16]]
gostos = movies[movies.columns[16:]]

In [50]:
caract.head(5)

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
0            0       0        0       0        0         0      0        0   
1            0       0        0       0        1         0      0        0   
2            0       0        0       0        1         0      0        0   
3            0       0        0       0        0         0      0        0   
4            0       0        0       0        1         0      0        0   

   Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
0       0          0         0      1          0  114.496547      7.930748  
1       0          0         0      1          0  110.140191     18.276555  
2       0          0         0      1          0  105.747597     16.582232  
3       0          0         1      1          0  126.131978     13.004553  
4       0          0         0      1          0   85.025469     14.418120

In [51]:
gostos.head(5)

Gostou
0       1
1       1
2       1
3       1
4       1

In [53]:
treino, teste, treino_labels, teste_labels = train_test_split(caract, gostos, test_size=0.1)
#treino, teste, treino_labels, teste_labels = train_test_split(caract, gostos)

In [54]:
type(treino)

pandas.core.frame.DataFrame

In [55]:
Counter(treino_labels['Gostou'])

Counter({1: 491, 0: 119})

In [56]:
Counter(teste_labels['Gostou'])

Counter({1: 52, 0: 16})

In [57]:
print('Gostou % {} do treino_label (deve manter a proporção +- 80%)'.format(404/(104+404)))

Gostou % 0.7952755905511811 do treino_label (deve manter a proporção +- 80%)


In [58]:
print('Gostou % {} do teste_label (deve manter a proporção +- 80%)'.format(139/(31+139)))

Gostou % 0.8176470588235294 do teste_label (deve manter a proporção +- 80%)


## Aula 3 Video 2 - A regressão logística

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.naive_bayes import MultinomialNB, GaussianNB

In [15]:
type(treino)

pandas.core.frame.DataFrame

In [16]:
treino[0:1]

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
104            0       0        0       0        0         0      0        0   

     Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
104       1          0         0      0          0  138.491788     10.331455

In [59]:
treino = np.array(treino).reshape(len(treino), 15)
teste = np.array(teste).reshape(len(teste), 15)

In [60]:
type(treino)

numpy.ndarray

In [61]:
treino[0]

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   1.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   1.        ,
         0.        , 151.3611696 ,  25.28566276])

In [62]:
type(treino_labels)

pandas.core.frame.DataFrame

In [63]:
treino_labels.head(5)

Gostou
16        1
52        0
608       1
239       1
290       1

In [64]:
treino_labels = treino_labels.values.ravel()
teste_labels = teste_labels.values.ravel()

In [65]:
type(treino_labels)

numpy.ndarray

In [66]:
treino_labels[0:5]

array([1, 0, 1, 1, 1])

In [67]:
treino_labels.shape

(610,)

#### Usando regressão logistica

In [68]:
modelo = LogisticRegression()
modelo.fit(treino, treino_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [69]:
previsoes = modelo.predict(teste)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [70]:
teste_labels.shape

(68,)

In [71]:
previsoes.shape

(68,)

In [72]:
acuracia = accuracy_score(teste_labels, previsoes)
acuracia

0.7647058823529411

In [31]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo.predict([zootopia])

array([1])

#### Usando Multinomial Naive Bayes

In [32]:
modelo_NB = MultinomialNB()

In [33]:
modelo_NB.fit(treino,treino_labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
previsoes_NB = modelo_NB.predict(teste)

In [35]:
acuracia = accuracy_score(teste_labels, previsoes_NB)
acuracia

0.7705882352941177

In [36]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_NB.predict([zootopia])

array([1])

#### EXTRA: Usando Gaussian Naive Bayes

In [73]:
modelo_GNB = GaussianNB()

In [74]:
modelo_GNB.fit(treino,treino_labels)

GaussianNB(priors=None)

In [75]:
previsoes_GNB = modelo_GNB.predict(teste)

In [76]:
acuracia = accuracy_score(teste_labels, previsoes_GNB)
acuracia

0.7205882352941176

In [41]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_GNB.predict([zootopia])

array([1])