## Aula 2 Video 1 - A regressão linear múltipla

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

Download Dataset: [movies_multilinear_reg.csv](https://s3.amazonaws.com/caelum-online-public/machine-learning-aprendizado-supervisionado/movies_multilinear_reg.csv)

In [2]:
movies = pd.read_csv('datasets/movies_multilinear_reg.csv')

In [3]:
type(movies)

pandas.core.frame.DataFrame

In [4]:
movies.head(10)

movieId                              Titulo  Documentary  Sci-Fi  Mystery  \
0        1                    Toy Story (1995)            0       0        0   
1        2                      Jumanji (1995)            0       0        0   
2        3             Grumpier Old Men (1995)            0       0        0   
3        4            Waiting to Exhale (1995)            0       0        0   
4        5  Father of the Bride Part II (1995)            0       0        0   
5        6                         Heat (1995)            0       0        0   
6        7                      Sabrina (1995)            0       0        0   
7        8                 Tom and Huck (1995)            0       0        0   
8        9                 Sudden Death (1995)            0       0        0   
9       10                    GoldenEye (1995)            0       0        0   

   Horror  Romance  Thriller  Crime  Fantasy  Comedy  Animation  Children  \
0       0        0         0      0        1       1          1         1   
1       0        0         0      0        1       0          0         1   
2       0        1         0      0        0       1          0         0   
3       0        1         0      0        0       1          0         0   
4       0        0         0      0        0       1          0         0   
5       0        0         1      1        0       0          0         0   
6       0        1         0      0        0       1          0         0   
7       0        0         0      0        0       0          0         1   
8       0        0         0      0        0       0          0         0   
9       0        0         1      0        0       0          0         0   

   Drama  Adventure     Duracao  Investimento   Bilheteria  
0      0          1  103.468310     11.048216  5623234.602  
1      0          1  112.337916     14.927678  5714951.757  
2      0          0  116.245732     27.114597  9524339.124  
3      1          0  120.317732      4.994242  6331568.779  
4      0          0  110.023572     19.142246  6409617.277  
5      0          0   97.324845      9.977311  4956557.317  
6      0          0   88.978893     14.257461  4654565.066  
7      0          1   78.536011      8.871800  3950017.325  
8      0          0  104.934703     29.112800  6850971.551  
9      0          1  105.899475      3.695241  5157865.850

In [5]:
movies.shape

(9125, 18)

In [6]:
filmes_independente = movies[movies.columns[2:17]]

In [7]:
type(filmes_independente)

pandas.core.frame.DataFrame

In [8]:
filmes_independente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9125 entries, 0 to 9124
Data columns (total 15 columns):
Documentary     9125 non-null int64
Sci-Fi          9125 non-null int64
Mystery         9125 non-null int64
Horror          9125 non-null int64
Romance         9125 non-null int64
Thriller        9125 non-null int64
Crime           9125 non-null int64
Fantasy         9125 non-null int64
Comedy          9125 non-null int64
Animation       9125 non-null int64
Children        9125 non-null int64
Drama           9125 non-null int64
Adventure       9125 non-null int64
Duracao         9125 non-null float64
Investimento    9125 non-null float64
dtypes: float64(2), int64(13)
memory usage: 1.0 MB


In [9]:
filmes_independente.head(5)

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
0            0       0        0       0        0         0      0        1   
1            0       0        0       0        0         0      0        1   
2            0       0        0       0        1         0      0        0   
3            0       0        0       0        1         0      0        0   
4            0       0        0       0        0         0      0        0   

   Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
0       1          1         1      0          1  103.468310     11.048216  
1       0          0         1      0          1  112.337916     14.927678  
2       1          0         0      0          0  116.245732     27.114597  
3       1          0         0      1          0  120.317732      4.994242  
4       1          0         0      0          0  110.023572     19.142246

In [10]:
filmes_dependente = movies[movies.columns[17:]]

In [11]:
type(filmes_dependente)

pandas.core.frame.DataFrame

In [12]:
filmes_dependente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9125 entries, 0 to 9124
Data columns (total 1 columns):
Bilheteria    9125 non-null float64
dtypes: float64(1)
memory usage: 71.4 KB


In [13]:
filmes_dependente.head(5)

Bilheteria
0  5623234.602
1  5714951.757
2  9524339.124
3  6331568.779
4  6409617.277

In [14]:
train, test, train_bilheteria, test_bilheteria = train_test_split(filmes_independente, filmes_dependente)

In [15]:
train.head()

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
7816            0       0        0       0        0         0      1        0   
1941            0       0        0       0        0         0      0        0   
224             0       0        0       0        1         0      0        0   
4213            0       0        0       0        0         0      0        0   
358             0       0        0       1        0         1      0        0   

      Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
7816       0          0         0      1          0   98.351855      8.238660  
1941       0          0         0      1          0  106.294929     13.217100  
224        1          0         0      0          0   88.645685     39.361534  
4213       1          0         0      0          0  106.541798     15.726841  
358        0          0         0      0          0  122.280001     26.691879

In [16]:
train.shape[0]

6843

In [17]:
test.shape[0]

2282

In [18]:
modelo = LinearRegression()
modelo.fit(train, train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

#### 1,Toy Story (1995),0,0,0,0,0,0,0,1,1,1,1,0,1,103.4683096,11.04821649,5623234.602

In [19]:
modelo.predict([[0,0,0,0,0,0,0,1,1,1,1,0,1,103.4683096,11.04821649]])

array([[5815379.64114834]])

In [20]:
modelo.score(train, train_bilheteria)

0.8295464321123391

In [21]:
modelo.coef_

array([[ 44929.64456355,  32394.34845339,  -8228.35928689,
        -37233.81249646,  44608.73053743,  31919.9310784 ,
          9230.88062511,   8452.26301406,    185.05625322,
         10949.54211508,   1059.40663064, -22684.62418549,
        -61537.07719614,  45824.15646724,  98839.17052764]])

In [22]:
modelo.intercept_

array([22925.88813887])

In [23]:
modelo.score(test, test_bilheteria)

0.8217558756580159

#### Zootopia
```
movieId,Titulo,Documentary,Sci-Fi,Mystery,Horror,Romance,Thriller,Crime,Fantasy,Comedy,Animation,Children,Drama,Adventure,Duracao,Investimento,Bilheteria
9999999,Zootopia,0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356,?????
```

In [24]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo.predict([zootopia])

array([[7764941.9392739]])

### Split dos dados com test_size=0.3

In [25]:
train, test, train_bilheteria, test_bilheteria = train_test_split(
    filmes_independente, filmes_dependente, test_size=0.3)

In [26]:
modelo_30 = LinearRegression()
modelo_30.fit(train,train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [27]:
modelo_30.score(test, test_bilheteria)

0.8196670689243407

In [28]:
zootopia = [0,0,0,0,0,0,0,0,1,1,1,0,1,145.5170642,3.451632127]
modelo.predict([zootopia])

array([[6982935.9908951]])

In [29]:
planeta_macaco = [0,1,0,0,0,0,0,0,0,0,0,0,0,150,5]
modelo.predict([planeta_macaco])

array([[7423139.55931644]])